# -*- coding: utf-8 -*-
"""try2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12N65F9oBxhEnNlKQL07782IxLxhGWE75
"""

!git clone https://github.com/pjreddie/darknet.git





cd /content/darknet

!ls

!make

!ls

!./darknet

! wget https://pjreddie.com/media/files/darknet19_448.conv.23

!git clone https://github.com/mohanrajmit/Safety_Detection.git

mv /content/darknet/Safety_Detection/dataset /content/darknet

!./darknet detector train cfg/obj.data cfg/yolo-voc.2.0.cfg darknet19_448.conv.23 -dont_show 0

